//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleBanking.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleBanking.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry that email is already in use..
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry that email / password combination was not recognized.
        /// </summary>
        public static string EmailCombinationInvalid {
            get {
                return ResourceManager.GetString("EmailCombinationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry that email is not recognized..
        /// </summary>
        public static string EmailDoesntExist {
            get {
                return ResourceManager.GetString("EmailDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an email address that is not empty..
        /// </summary>
        public static string EmailNotEmptyMessage {
            get {
                return ResourceManager.GetString("EmailNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid email address which includes an &apos;@&apos;-sign as well as a domain (i.e. &apos;.com&apos;). .
        /// </summary>
        public static string EmailNotValidFormatMessage {
            get {
                return ResourceManager.GetString("EmailNotValidFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid email address..
        /// </summary>
        public static string EmailNotValidGenericMessage {
            get {
                return ResourceManager.GetString("EmailNotValidGenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred on and we couldn&apos;t process that request..
        /// </summary>
        public static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your emai address:.
        /// </summary>
        public static string GetUserEmail {
            get {
                return ResourceManager.GetString("GetUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password:.
        /// </summary>
        public static string GetUserPassword {
            get {
                return ResourceManager.GetString("GetUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Welcome to the Bank of Nate!
        ///.
        /// </summary>
        public static string InitialGreeting {
            get {
                return ResourceManager.GetString("InitialGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your input was invalid. Please try again below:  .
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address:.
        /// </summary>
        public static string NewUserGetEmail {
            get {
                return ResourceManager.GetString("NewUserGetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of your home town:.
        /// </summary>
        public static string NewUserGetHomeTown {
            get {
                return ResourceManager.GetString("NewUserGetHomeTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password meeting the following criteria:
        ///  - at least 12 characters long
        ///  - at least 1 uppercase non-numeric character
        ///  - at least 1 lowercase non-numeric character
        ///  - at least 1 numeric character
        ///  - at least one special character .
        /// </summary>
        public static string NewUserGetPassword {
            get {
                return ResourceManager.GetString("NewUserGetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a 4 to 20 character-length password containing letters, numbers, one uppercase letter, and one special character..
        /// </summary>
        public static string PasswordMustHaveNecessaryComponents {
            get {
                return ResourceManager.GetString("PasswordMustHaveNecessaryComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Please provide a password that is not empty..
        /// </summary>
        public static string PasswordNotEmptyMessage {
            get {
                return ResourceManager.GetString("PasswordNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Please provide a valid password..
        /// </summary>
        public static string PasswordNotValidGenericMessage {
            get {
                return ResourceManager.GetString("PasswordNotValidGenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///***********************************************************
        ///Your are currently logged in. Please select an option:
        ///    - Press [4] to view recent transactions
        ///    - Press [5] to deposit money
        ///    - Press [6] to withdraw money
        ///    - Press [3] to sign out and exit
        ///***********************************************************
        ///.
        /// </summary>
        public static string UserOptionsForLoggedInUser {
            get {
                return ResourceManager.GetString("UserOptionsForLoggedInUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***********************************************************
        ///Please select on of the following options:
        ///    - Press [1] to log into the system.
        ///    - Press [2] to create a new account.
        ///    - Press [3] to exit
        ///***********************************************************.
        /// </summary>
        public static string UserOptionsForNonLoggedInUser {
            get {
                return ResourceManager.GetString("UserOptionsForNonLoggedInUser", resourceCulture);
            }
        }
    }
}
