//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleBanking.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleBanking.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =================================================================
        ///|/^\\%&amp;%&amp;%&amp;%&amp;%&amp;%&amp;%&amp;%&amp;{ Federal Reserve Note }%&amp;%&amp;%&amp;%&amp;%&amp;%&amp;%&amp;%&amp;//^\%|
        ///|inn\)===============------------------------===============(/inn\|
        ///||UU/              { UNITED STATES OF AMERICA }              \|UU/|
        ///|\-/     ~~~~~~~~   ~~~~~~~~~~=====~~~~~~~~~~~  P8188928246   \-/&amp;|
        ///|//)     ~~~_~~~~~          // ___ \\                         (\\%|
        ///|(/  13    /_\             // /_ _\ \\           ~~~~~~~~  13  \)&amp;|
        ///|\\       // \\           :| |/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AsciiArtDollarBill {
            get {
                return ResourceManager.GetString("AsciiArtDollarBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Welcome to the Bank of Nate!
        ///.
        /// </summary>
        public static string InitialGreeting {
            get {
                return ResourceManager.GetString("InitialGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I didn&apos;t understand that request....
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address:.
        /// </summary>
        public static string NewUserGetEmail {
            get {
                return ResourceManager.GetString("NewUserGetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of your home town:.
        /// </summary>
        public static string NewUserGetHomeTown {
            get {
                return ResourceManager.GetString("NewUserGetHomeTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password meeting the following criteria:
        ///  - at least 12 characters long
        ///  - at least 1 uppercase non-numeric character
        ///  - at least 1 lowercase non-numeric character
        ///  - at least 1 numeric character
        ///  - at least one special character .
        /// </summary>
        public static string NewUserGetPassword {
            get {
                return ResourceManager.GetString("NewUserGetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Please select on of the following options:
        ///    - Press [1] to log into the system.
        ///    - Press [2] to create a new account..
        /// </summary>
        public static string UserOptionsChoiceSet1 {
            get {
                return ResourceManager.GetString("UserOptionsChoiceSet1", resourceCulture);
            }
        }
    }
}
